name: Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (leave empty for latest)'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: 'docker-compose.yml'
          target: '${{ vars.DEPLOY_PATH }}/docker-compose.yml'

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "ENV_VAR1=${{ secrets.ENV_VAR1 }}" > ${{ vars.DEPLOY_PATH }}/.env
            echo "ENV_VAR2=${{ secrets.ENV_VAR2 }}" >> ${{ vars.DEPLOY_PATH }}/.env
            docker-compose -f ${{ vars.DEPLOY_PATH }}/docker-compose.yml down
            if [ "${{ github.event.inputs.tag }}" == "" ]; then
              TAG="latest"
            else
              TAG="${{ github.event.inputs.tag }}"
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/ferme-en-bray-frontend-frontend:$TAG
            docker pull ${{ secrets.DOCKER_USERNAME }}/ferme-en-bray-frontend-backend:$TAG
            docker pull ${{ secrets.DOCKER_USERNAME }}/ferme-en-bray-frontend-nginx:$TAG
            docker-compose --env-file ${{ vars.DEPLOY_PATH }}/.env -f ${{ vars.DEPLOY_PATH }}/docker-compose.yml up -d