name: Deploy

on:
  workflow_dispatch:
    inputs:
      frontend:
        type: boolean
        required: false
        default: false
        description: Deploy frontend
      backend:
        type: boolean
        required: false
        default: false
        description: Deploy backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy backend files
        if: ${{ github.event.inputs.backend == true }}
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: 'backend'
          target: '${{ vars.DEPLOY_BACKEND_PATH }}'

      - name: Deploy frontend to server
        if: ${{ github.event.inputs.backend == true }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            source ${{ vars.SOURCE_ENV_BACKEND_PATH }}
            cd ${{ vars.DEPLOY_BACKEND_PATH }}
            echo "ENV_VAR1=${{ secrets.ENV_VAR1 }}" > ${{ vars.DEPLOY_BACKEND_PATH }}/.env
            echo "ENV_VAR2=${{ secrets.ENV_VAR2 }}" >> ${{ vars.DEPLOY_BACKEND_PATH }}/.env
            echo "Installing dependencies"
            npm install

      - name: Copy frontend files
        if: ${{ github.event.inputs.frontend == true }}
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: 'frontend'
          target: '${{ vars.DEPLOY_FRONTEND_PATH }}'

      - name: Deploy frontend to server
        if: ${{ github.event.inputs.frontend == true }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            source ${{ vars.SOURCE_ENV_FRONTEND_PATH }}
            cd ${{ vars.DEPLOY_FRONTEND_PATH }}
            echo "ENV_VAR1=${{ secrets.ENV_VAR1 }}" > ${{ vars.DEPLOY_FRONTEND_PATH }}/.env
            echo "ENV_VAR2=${{ secrets.ENV_VAR2 }}" >> ${{ vars.DEPLOY_FRONTEND_PATH }}/.env
            echo "Installing dependencies"
            npm install
            echo "Building"
            npm run build
            rm -rf output
            mkdir output
            echo "Copying files"
            cp -r ".next/standalone" "output/"
            cp -r "public" "output/public"
            cp ".next/static" "output/.next/static"
            echo "Deleting unnecessary files"
            find . -mindepth 1 -maxdepth 1 -not -name "output" -exec rm -rf {} \;
