name: 🚀 Deploy

on:
  workflow_dispatch:
    inputs:
      frontend:
        type: boolean
        required: false
        default: false
        description: Deploy frontend
      backend:
        type: boolean
        required: false
        default: false
        description: Deploy backend
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  log-modified-files:
    if : github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Log modified files
        run: |
          echo "Modified files:"
          echo "${{ toJSON(github.event.commits.*.modified) }}"

  deploy-backend:
    name: 🛠️ Deploy Backend
    if: ${{ github.event.inputs.backend == 'true' || (github.event_name == 'push' && contains(github.event.commits.*.modified, 'backend/')) }}
    uses: ./.github/workflows/deploy-common.yml
    secrets: inherit
    with:
      service: 'backend'
      deploy_path: ${{ vars.DEPLOY_BACKEND_PATH }}
      source_env_path: ${{ vars.SOURCE_ENV_BACKEND_PATH }}
      is_frontend: false

  deploy-frontend:
    name: 🌐 Deploy Frontend
    if: ${{ github.event.inputs.frontend == 'true' || (github.event_name == 'push' && contains(github.event.commits.*.modified, 'frontend/')) }}
    uses: ./.github/workflows/deploy-common.yml
    secrets: inherit
    with:
      service: 'frontend'
      deploy_path: ${{ vars.DEPLOY_FRONTEND_PATH }}
      source_env_path: ${{ vars.SOURCE_ENV_FRONTEND_PATH }}
      is_frontend: true